version: '3.2'

services:

  stack-router:
    image: flavioaiello/swarm-router:latest
    environment:
      - HTTP_PORTS=8080
      - TLS_PORTS=8443
      - DNS_BACKEND_FQDN=false
      - HTTP_BACKENDS_PORT=whoami:8000
    networks:
      default:
      swarm_routing:
        aliases:
          - whoami.stack-a.vcap.me
    healthcheck:
      test: nc -w 7 -zvv 0.0.0.0 1111
      interval: 30s
      timeout: 30s
      retries: 20
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 8M
        limits:
          memory: 8M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

  whoami:
    image: jwilder/whoami:latest

networks:
  default:
    internal: true
    driver: overlay
  swarm_routing:
    external: true
