version: '3'

services:

  swarm-router:
    image: flavioaiello/swarm-router:latest
    environment:
      - HTTP_PORTS=80
      - TLS_PORTS=8443
      - HTTP_BACKENDS_PORT=portainer:9000 #default is 8080 can be overridden by startswith:xxxx 
    ports:
      - "80:80"
      - "443:443"
      - "1111:1111"
    networks:
      - default
      - routing
    restart: always

  portainer:
    image: portainer/portainer
    depends_on:
      - swarm-router
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth -H unix:///var/run/docker.sock
    networks:
      default:
        aliases:
          - portainer.vcap.me
    restart: always

networks:
  default:
    driver: overlay
  routing:
    driver: overlay
