version: '3.2'

services:

  swarm-router:
    image: swarm-router:latest
    environment:
      - HTTP_BACKENDS_PORT=portainer:9000 nexus:8081 swarm-router:1111 whoami:8000
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
      - "1111:1111"
    networks:
      default:
      routing:
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
        limits:
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  portainer:
    image: portainer/portainer
    depends_on:
      - swarm-router
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      default:
        aliases:
          - portainer.localtest.me
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 128M
        limits:
          cpus: '1.00'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

networks:
  default:
    driver: overlay
  routing:
    driver: overlay
    attachable: true
